# Site settings
title: jagthebeetle | Things & Thinks
description: >
  Jonathan Alvarez-Gutierrez muses on transcendence, thought, language, and JavaScript. In his free time, he works in the digital analytics industry.
url: "https://poet.computer"

# Build settings
markdown: kramdown
sass:
  style: compressed
exclude:
  - makefile
  - README.md
gems:
  - jekyll-sitemap
