# Site settings
title: jagthebeetle | Things & Thinks
description: >
  Jonathan Alvarez-Gutierrez muses on transcendence, thought, language, and JavaScript. In his free time, he works in the digital analytics industry.
url: "https://jagthebeetle.github.io"

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
