# Site settings
title: Arts & Crufts
description: >
  Jonathan Alvarez-Gutierrez's site on Google Analytics, JavaScript, writing,
  and general brooding. Jonathan is a Solutions Consultant at Google in his
  free time, but is otherwise preoccupied with transcendence, (his) thoughts 
  language, games, stories, and music - all of which makes him an unfortunately
  dull and commonplace individual. He notes that the word 'legend' means
  'having to be read.' This site is legend.
url: "https://jagthebeetle.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
